import type { StorefrontBootstrap } from '@jersey-commerce/types';

export const fallbackStore: StorefrontBootstrap = {
  tenant: {
    slug: 'demo-jersey-store',
    name: 'Demo Jersey Store',
    legalName: 'Demo Jersey Store LLP',
    currency: 'INR',
    timezone: 'Asia/Kolkata',
    contactPhone: '+91 98765 00000',
    contactEmail: 'hello@demo.local',
    address: '12 Stadium Road',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'IN',
    postalCode: '400001',
  },
  theme: {
    primaryColor: '#0f172a',
    secondaryColor: '#f97316',
    accentColor: '#ea580c',
    backgroundColor: '#F2F2F2',
    foregroundColor: '#0f172a',
    headingFont: 'Inter',
    bodyFont: 'Inter',
    logo: '/demo/logo.png',
    favicon: '/demo/favicon.png',
  },
  website: {
    contactPhone: '+91 98765 00000',
    contactEmail: 'hello@demo.local',
    contactAddress: '12 Stadium Road, Mumbai',
    socialLinks: {},
    businessHours: null,
    seoTitle: 'Demo Jersey Store',
    seoDescription: 'Premium kits. Built for fans.',
    homepage: {
      sections: [
        {
          type: 'hero',
          enabled: true,
          heading: 'Your new kit is here +',
          subheading: 'A limited drop cut for match day. Premium fabric, sharp prints, and an exclusive offer on the full catalog.',
          ctaLabel: 'Shop Now',
          ctaHref: '/products',
          image: '/demo/hero.jpg',
        },
        {
          type: 'featured-categories',
          enabled: true,
          heading: 'Collections',
          categorySlugs: ['football', 'cricket', 'ipl', 'custom-jerseys'],
        },
        {
          type: 'promo-banner',
          enabled: true,
          heading: 'Custom / Exclusive',
          subheading: 'Get up to 40% off selected jerseys this week.',
          ctaLabel: 'Shop custom jerseys',
          ctaHref: '/category/custom-jerseys',
          image: '/demo/promo.jpg',
        },
        {
          type: 'cta',
          enabled: true,
          heading: 'Find your kit',
          subheading: 'Club, national, IPL, and custom kits in one catalog.',
          ctaLabel: 'Browse all jerseys',
          ctaHref: '/products',
          image: '/demo/cta.jpg',
        },
      ],
    },
  },
  navigation: [
    { id: 'nav-football', name: 'Football', slug: 'football', parentId: null, status: 'ACTIVE', sortOrder: 1 },
    { id: 'nav-cricket', name: 'Cricket', slug: 'cricket', parentId: null, status: 'ACTIVE', sortOrder: 2 },
    { id: 'nav-custom', name: 'Custom Jerseys', slug: 'custom-jerseys', parentId: null, status: 'ACTIVE', sortOrder: 3 },
  ],
};
