import { DEMO_CTA_IMAGE, DEMO_HERO_IMAGE, DEMO_KITS_IMAGE } from './demo-media';
import { DEFAULT_STOREFRONT_CHROME, DEFAULT_STOREFRONT_FOOTER, type StorefrontBootstrap } from '@jersey-commerce/types';
import { JERZYFY_DARK_MATCHDAY } from './jerzyfy-brand';

export const fallbackStore: StorefrontBootstrap = {
  tenant: {
    slug: 'demo-jersey-store',
    name: 'Jerzyfy',
    legalName: 'Jerzyfy LLP',
    currency: 'INR',
    timezone: 'Asia/Kolkata',
    contactPhone: '+91 98765 00000',
    contactEmail: 'hello@jerzyfy.local',
    address: '12 Stadium Road',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'IN',
    postalCode: '400001',
  },
  theme: {
    ...JERZYFY_DARK_MATCHDAY,
    headingFont: 'Instrument Serif',
    bodyFont: 'Inter',
    logo: '/demo/logo.png',
    favicon: '/demo/favicon.png',
  },
  website: {
    contactPhone: '+91 98765 00000',
    contactEmail: 'hello@jerzyfy.local',
    contactAddress: '12 Stadium Road, Mumbai',
    socialLinks: {},
    businessHours: null,
    seoTitle: 'Jerzyfy — Football Jerseys',
    seoDescription: 'Shop club, national, kids, and custom football jerseys at Jerzyfy.',
    homepage: {
      sections: [
        {
          type: 'hero',
          enabled: true,
          heading: 'Wear the game',
          subheading: 'Match-day kits for the stands, the street, and every kick-off.',
          ctaLabel: 'Shop jerseys',
          ctaHref: '/products',
          image: DEMO_HERO_IMAGE,
          slides: [
            {
              id: 'hero-1',
              image: DEMO_HERO_IMAGE,
              heading: 'Wear the game',
              subheading: 'Match-day kits for the stands, the street, and every kick-off.',
              ctaLabel: 'Shop jerseys',
              ctaHref: '/products',
            },
            {
              id: 'hero-2',
              image: DEMO_CTA_IMAGE,
              heading: 'Club kits for every stand',
              subheading: 'Home, away, and third kits inspired by the game.',
              ctaLabel: 'Shop club jerseys',
              ctaHref: '/category/club-jerseys',
            },
            {
              id: 'hero-3',
              image: DEMO_KITS_IMAGE,
              heading: 'National colours',
              subheading: 'Represent with breathable national team-inspired football jerseys.',
              ctaLabel: 'Shop national kits',
              ctaHref: '/category/national-jerseys',
            },
          ],
        },
        {
          type: 'marquee',
          enabled: true,
          heading: 'Club · National · Custom · Kids',
          subheading: 'Wear the game · Match day ready',
        },
        {
          type: 'statement',
          enabled: true,
          heading: 'WEAR THE GAME',
          subheading: 'Cut for the pitch. Lived beyond the final whistle.',
        },
        {
          type: 'new-arrivals',
          enabled: true,
          heading: 'Latest kits',
        },
        {
          type: 'promo-banner',
          enabled: true,
          heading: 'Floodlit football',
          subheading: 'Replica-inspired football jerseys with durable knits and match-day fit.',
          ctaLabel: 'Browse catalog',
          ctaHref: '/products',
        },
        {
          type: 'featured-products',
          enabled: true,
          heading: 'Featured kits',
        },
        {
          type: 'featured-categories',
          enabled: true,
          heading: 'Shop by kit',
          categorySlugs: ['club-jerseys', 'national-jerseys', 'kids-jerseys', 'custom-jerseys'],
        },
        {
          type: 'trust',
          enabled: true,
          heading: 'Built for match day',
          items: [
            { title: 'Free delivery', description: 'Complimentary delivery on orders above ₹2,000.' },
            { title: 'Secure checkout', description: 'Pay safely online with Razorpay.' },
            { title: 'Breathable knits', description: 'Moisture-wicking fabrics made for long wears.' },
            { title: 'Easy returns', description: 'Contact the store if a size does not fit as expected.' },
          ],
        },
        {
          type: 'cta',
          enabled: true,
          heading: 'Find your jersey',
          subheading: 'Club, national, kids, and custom football kits in one catalog.',
          ctaLabel: 'Browse all jerseys',
          ctaHref: '/products',
          image: DEMO_CTA_IMAGE,
        },
      ],
    },
    footer: DEFAULT_STOREFRONT_FOOTER,
    chrome: DEFAULT_STOREFRONT_CHROME,
  },
  navigation: [
    { id: 'nav-football', name: 'Football Jerseys', slug: 'football-jerseys', parentId: null, status: 'ACTIVE', sortOrder: 1 },
    { id: 'nav-club', name: 'Club Jerseys', slug: 'club-jerseys', parentId: 'nav-football', status: 'ACTIVE', sortOrder: 2 },
    { id: 'nav-national', name: 'National Jerseys', slug: 'national-jerseys', parentId: 'nav-football', status: 'ACTIVE', sortOrder: 3 },
    { id: 'nav-custom', name: 'Custom Jerseys', slug: 'custom-jerseys', parentId: 'nav-football', status: 'ACTIVE', sortOrder: 4 },
  ],
  auth: {
    passwordLogin: true,
    emailOtp: false,
    smsOtp: false,
    googleSignIn: false,
  },
  payments: {
    razorpay: false,
    razorpayKeyId: null,
  },
};
