FROM node:20-alpine AS base
WORKDIR /app

FROM base AS deps
COPY package.json package-lock.json ./
COPY apps/api/package.json apps/api/package.json
COPY apps/storefront/package.json apps/storefront/package.json
COPY apps/admin/package.json apps/admin/package.json
COPY apps/pos/package.json apps/pos/package.json
COPY packages/types/package.json packages/types/package.json
COPY packages/validation/package.json packages/validation/package.json
COPY packages/config/package.json packages/config/package.json
COPY packages/utils/package.json packages/utils/package.json
COPY packages/ui/package.json packages/ui/package.json
RUN npm ci

FROM deps AS build
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_PORTAL=admin
ARG NEXT_PUBLIC_DEFAULT_TENANT_SLUG=demo-jersey-store
ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_OPTIONS=--max-old-space-size=1536
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
ENV NEXT_PUBLIC_PORTAL=${NEXT_PUBLIC_PORTAL}
ENV NEXT_PUBLIC_DEFAULT_TENANT_SLUG=${NEXT_PUBLIC_DEFAULT_TENANT_SLUG}
COPY tsconfig.base.json ./
COPY packages ./packages
COPY apps/admin ./apps/admin
COPY apps/pos ./apps/pos
RUN mkdir -p apps/admin/public apps/pos/public
RUN npm run build -w @jersey-commerce/types -w @jersey-commerce/validation -w @jersey-commerce/config -w @jersey-commerce/utils
RUN npm run build -w @jersey-commerce/admin
RUN npm run build -w @jersey-commerce/pos

FROM nginx:1.27-alpine
COPY --from=build /app/apps/admin/out /usr/share/nginx/admin
COPY --from=build /app/apps/pos/out /usr/share/nginx/pos
COPY infra/docker/nginx.conf /etc/nginx/nginx.conf
COPY infra/docker/nginx-entrypoint.sh /nginx-entrypoint.sh
RUN chmod +x /nginx-entrypoint.sh
EXPOSE 80 3001 3002 4000
ENTRYPOINT ["/nginx-entrypoint.sh"]
