export const ROLE_CODES = [
  'SUPER_ADMIN',
  'OWNER',
  'MANAGER',
  'CASHIER',
  'INVENTORY_MANAGER',
  'WEBSITE_MANAGER',
] as const;

export type RoleCode = (typeof ROLE_CODES)[number];

export const PERMISSIONS = [
  'products.read',
  'products.create',
  'products.update',
  'products.delete',
  'categories.read',
  'categories.create',
  'categories.update',
  'categories.delete',
  'inventory.read',
  'inventory.adjust',
  'inventory.manage',
  'sales.read',
  'sales.create',
  'sales.cancel',
  'sales.discount',
  'sales.refund',
  'orders.read',
  'orders.create',
  'orders.update',
  'orders.cancel',
  'customers.read',
  'customers.create',
  'customers.update',
  'customers.delete',
  'customers.notes',
  'customers.tags',
  'purchases.read',
  'purchases.create',
  'purchases.update',
  'suppliers.read',
  'suppliers.create',
  'reports.read',
  'users.read',
  'users.manage',
  'settings.read',
  'settings.manage',
  'website.read',
  'website.update',
  'promoCodes.read',
  'promoCodes.manage',
  'pos.access',
  'pos.session.open',
  'pos.session.close',
] as const;

export type PermissionKey = (typeof PERMISSIONS)[number];
