import type { PermissionCode, RoleCode } from '@jersey-commerce/types';
import { PERMISSION_CODES } from '@jersey-commerce/types';

export const DEFAULT_ROLE_PERMISSIONS: Record<RoleCode, readonly PermissionCode[] | 'ALL'> = {
  OWNER: 'ALL',
  MANAGER: PERMISSION_CODES.filter((code) => code !== 'settings.manage'),
  CASHIER: [
    'products.read',
    'categories.read',
    'customers.read',
    'customers.create',
    'sales.read',
    'sales.create',
    'sales.refund',
    'payments.read',
    'payments.create',
    'payments.refund',
    'orders.read',
    'orders.create',
    'orders.update',
    'orders.cancel',
    'inventory.read',
    'pos.access',
    'pos.session.open',
    'pos.session.close',
  ],
  INVENTORY_MANAGER: [
    'products.read',
    'products.create',
    'products.update',
    'categories.read',
    'categories.create',
    'categories.update',
    'inventory.read',
    'inventory.adjust',
    'inventory.manage',
    'purchases.read',
    'purchases.create',
    'purchases.update',
    'purchases.receive',
    'purchases.cancel',
    'suppliers.read',
    'suppliers.create',
    'suppliers.update',
    'suppliers.delete',
    'supplierPayments.read',
    'supplierPayments.create',
    'sales.read',
    'payments.read',
    'orders.read',
    'customers.read',
  ],
  WEBSITE_MANAGER: [
    'products.read',
    'products.create',
    'products.update',
    'categories.read',
    'categories.update',
    'website.read',
    'website.update',
    'customers.read',
    'orders.read',
    'orders.create',
    'orders.update',
    'orders.cancel',
  ],
};
